### ISSUE TITLE
Script got stuck without output any file

### ISSUE THREAD

**Issue by protonaut** [facorazza/Passwords2Bitwarden#1]
Hallo, I just wanted to use the converter and I followed the procedere but the script got stuck withpout any file output.
I received the following error report: 

 File "/home/Passwords2Bitwarden/main.py", line 77, in <module>
    cli()
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/rafael-user/Downloads/Passwords2Bitwarden/main.py", line 24, in cli
    if row["ParentLabel"] == "Home":
KeyError: 'ParentLabel'

Any suggestion how to get the converted file because I strongly want to leave nextcloud passwords. But I have 199 passwords....

**Comment by facorazza** [comment]
It looks like there is no `ParentLabel` in `Folders.csv`. What version of the passwords app are you using?
Do you have any entry in `Folders.csv`?

**Comment by protonaut** [comment]
Thanks for the responce. 
Actually I have the version 2023.3.20 of nextcloud passwords.
I just removed all my folders and moved the passwords to the root.
When I export the passwords I get a csv-file without compression, which the python script  refuses to touch.

But I just saw that the gitfolder of Passwords2Bitwarden changed 3 days ago, so I'm going to reinstall it and try my best.

**Comment by facorazza** [comment]
The change from 3 days ago didn't touch the actual code.

Are you following the instructions in the readme? You're not supposed to unzip the downloaded archive.

**Comment by protonaut** [comment]
Yes, I did. Without folders I got the log info, that a folder file ist missing.
So I recreated one test-folder and got this massage:

python main.py Passwörter+Ordner+Tags_24.3.2023.zip 
Traceback (most recent call last):
  File "/home/rafael-user/Downloads/Passwords2Bitwarden/main.py", line 77, in <module>
    cli()
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/rafael-user/Downloads/Passwords2Bitwarden/main.py", line 24, in cli
    if row["ParentLabel"] == "Home":
KeyError: 'ParentLabel'

Now I'm going to fill the folder with one entry, maybe this will be a gamechanger in this trial and error.

**Comment by protonaut** [comment]
I guessed that maybe an empty folder is the problem, but it doesn't seem so. The same error appears when I fill the folder.

**Comment by facorazza** [comment]
The error is about the csv structure.
It could very well be that they changed the data model.
Could you paste here the first row of the Folders.csv?
It should only contain the field names

**Comment by protonaut** [comment]
Next move: updating the nextcloud app: passwords new version available: 2023.3.21
But the same as before.
passwords.csv/ Folders.csv / Tags.csv were written.
Tags.csv is empty because I didn't have any tags. 
Folderss.csv contains the one folder.
Passwords contains als the passwords

No *.json file was created.

**Comment by protonaut** [comment]
> The change from 3 days ago didn't touch the actual code.
> 
> Are you following the instructions in the readme? You're not supposed to unzip the downloaded archive.

Of couse. main.py is getting the .zip file.

**Comment by facorazza** [comment]
What's the folder structure inside the archive?

**Comment by protonaut** [comment]
![Bildschirmfoto vom 2023-03-24 19-04-53](https://user-images.githubusercontent.com/75339252/227605306-cda7c892-2553-4cdc-8931-f8cf048d70de.png)

**Comment by facorazza** [comment]
Good can you paste the first row of the Folders.csv file here?

**Comment by protonaut** [comment]
![Bildschirmfoto vom 2023-03-24 19-21-43](https://user-images.githubusercontent.com/75339252/227608525-88cb961f-a158-47b8-8e3e-6a4876db830d.png)

**Comment by facorazza** [comment]
Ok so the fact that the column names are not in English is already an issue.
I guess überordner should be parentlabel.
Could you try switching the language in nextcloud to English and export the passwords again?

**Comment by facorazza** [comment]
@protonaut did it work?

**Comment by protonaut** [comment]
Sorry, I was out. I can try.

**Comment by protonaut** [comment]
![Bildschirmfoto vom 2023-03-24 21-19-31](https://user-images.githubusercontent.com/75339252/227632012-89fbab59-91e5-4f2e-81c5-9e8aeeeb7ed4.png)

**Comment by protonaut** [comment]
Okay, this was the right hint. It worked. 
Germanspecific Letters were the problem.
Thx a lot for your support. 
![Bildschirmfoto vom 2023-03-24 21-30-19](https://user-images.githubusercontent.com/75339252/227632967-dd1827b6-23af-40b5-833d-6b936ff70562.png)

**Comment by facorazza** [comment]
Great! I'll update the README to include that the English language should be used.
Thank you for opening the issue

**Comment by facorazza** [comment]
Closing with [8fd0709](https://github.com/facorazza/Passwords2Bitwarden/commit/8fd07093053dca7fd154d67c5f61aa009dcc3d5d)
