### ISSUE TITLE
Fails if there are no favorite passwords

### ISSUE THREAD

**Issue by Bitals** [facorazza/Passwords2Bitwarden#4]
```
python main.py Passwords+Folders_02_12_2023.zip
Traceback (most recent call last):
  File "/home/bitals/GitClonedRepos/Passwords2Bitwarden/main.py", line 77, in <module>
    cli()
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bitals/GitClonedRepos/Passwords2Bitwarden/main.py", line 56, in cli
    "favorite": True if row["Favorite"] == "true" else False,
                        ~~~^^^^^^^^^^^^
KeyError: 'Favorite'

```

Fixed by commenting out the line 56:
```
                "favorite": True if row["Favorite"] == "true" else False,

```

Some additional check should probably be added. I might have time to test with a couple of cases and write a PR later, but no guarantee.

**Comment by eveiscoull** [comment]
Confirmed was having the same issue, this resolved it ^

**Comment by facorazza** [comment]
> Fixed by commenting out the line 56:
                "favorite": True if row["Favorite"] == "true" else False,

By commenting out that line, you would remove the favorite property of a password.
I have included a check on the existence of the `Favorite` key to fix this.

**Comment by Bitals** [comment]
> By commenting out that line, you would remove the favorite property of a password.

Yep, that's a quick dirty fix because I don't have any favorite passwords, which triggered the problem in the first place.

Thanks for a proper fix.
